categories:
  - title: '🐛 Fixes'
    label: 'Bugfix'
  - title: '🚀 Additions'
    label: 'Feature'
  - title: '🧭 Changes'
    label: 'Enhancement'
  - title: '🤖 Dependency updates'
    label: 'Renovate'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@'
exclude-contributors:
  - 'renovate'
template: |
  ## Changes

  $CHANGES
