name: ${project.artifactId}
main: com.thevoxelbox.voxelsniper.VoxelSniper
version: ${project.build.version}
website: ${project.url}
authors: [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage]
description: ${project.description}
softdepend: [VoxelModPackPlugin]
commands:
  paint:
    description: Change the selected painting to another painting.
    usage: |
           /<command>
           Example: /<command> -- Cycles through paintings. You must be adjacent to the painting and aiming at it.
  goto:
    description: Warps to the specified coordinates.
    permission: voxelsniper.goto
    usage: |
           /<command> [X] [Z]
           Example: /<command> 100 -100 -- Takes the user to the coordinates X: 100, Z: -100. The Y-coordinate will always be 1 more than the Y-coordinate of the highest block at the X and Z-coordinates provided.
  u:
    description: Undoes the last snipe.
    permission: voxelsniper.sniper
    usage: |
           /<command>
           Example: /<command> -- Undoes your most recent snipe.
  uu:
    description: UndoUser undoes another sniper user's snipes.
    permission: voxelsniper.sniper
    usage: |
           /<command> [playername]
           Example: /<command> bads -- Undoes BadSniper's last snipe.  BadSniper must be online for name detection to function. Truncation allowed.
  d:
    description: VoxelSniper Default.
    permission: voxelsniper.sniper
    usage: |
           /<command>
           Example: /<command> -- Resets the brush settings to their default values.
  p:
    description: Voxelsniper performer.
    permission: voxelsniper.sniper
    aliases: [perf, performer]
    usage: |
           /<command>
           Example: /<command> -- Sets the performer of the current brush to "m".
           /<command> <performer>
           Example: /<command> -- Sets the performer of the current brush to <performer>.
  vs:
    description: VoxelSniper Settings.
    permission: voxelsniper.sniper
    usage: |
           /<command>
           Example: /<command> -- Returns the current brush settings.
  vc:
    description: VoxelCentroid.
    permission: voxelsniper.sniper
    usage: |
           /<command>
           Example: /<command> -1 -- Sets the Clone Cylinder's Y value for the base relative to the Clone Point.
  vh:
    description: VoxelHeight.
    permission: voxelsniper.sniper
    usage: |
           /<command> [voxel-height]
           Example: /<command> -- Sets the brush height.
  vi:
    description: VoxelInk (Data Value).
    permission: voxelsniper.sniper
    usage: |
           /<command> [0-16]
           Example: /<command> -- sets a data value of 6 (e.g. pink wool).
  vr:
    description: VoxelReplace.
    permission: voxelsniper.sniper
    usage: |
           /<command> [0-159]
           Example: /<command> 12 -- Sets a replace brush to select sand blocks for replacement.
  vl:
    description: VoxelBlockExclusion list
    permission: voxelsniper.sniper
    usage: |
      /<command>
      Example: /<command> 89 -5 -- Adds glowstone to the voxel list and removes planks from the voxel list.
  vir:
    description: VoxelInkReplace.
    permission: voxelsniper.sniper
    usage: |
           /<command> [0-16]
           Example: /<command> 12 -- Sets a replace ink brush to select data 6 blocks for replacement.
  v:
    description: Voxel input.
    permission: voxelsniper.sniper
    usage: |
           /<command> [0-159]
           Example: /<command> 1 -- Loads the sniper with Stone blocks.
  b:
    description: Brush.
    permission: voxelsniper.sniper
    usage: |
           /<command> [brush-size]
           Example: /<command> 5 -- Sets a brush radius size of 5 (11 spaces across).
           Example: /<command> b cm -- Sets your brush to the Ball Brush with the combo-mat performer.
  btool:
    description: Brush Tool Command.
    permission: voxelsniper.sniper
    usage : |
            /<command> -- Prints out command usage information.
  vchunk:
    description: Update the chunk you are standing in.
    usage: |
           /<command>
           Example: /<command> -- Loads the chunk you're standing in.
permissions:
  voxelsniper.sniper:
    default: op
  voxelsniper.ignorelimitations:
    default: op
  voxelsniper.goto:
    default: op
  voxelsniper.brush.*:
    default: op
    children:
      voxelsniper.brush.ball
      voxelsniper.brush.biome
      voxelsniper.brush.blendball
      voxelsniper.brush.blenddisc
      voxelsniper.brush.blendvoxel
      voxelsniper.brush.blendvoxeldisc
      voxelsniper.brush.blob
      voxelsniper.brush.blockreset
      voxelsniper.brush.blockresetsurface
      voxelsniper.brush.canyon
      voxelsniper.brush.canyonselection
      voxelsniper.brush.checkervoxeldisc
      voxelsniper.brush.cleansnow
      voxelsniper.brush.clonestamp
      voxelsniper.brush.comet
      voxelsniper.brush.copypasta
      voxelsniper.brush.cylinder
      voxelsniper.brush.disc
      voxelsniper.brush.discface
      voxelsniper.brush.dome
      voxelsniper.brush.drain
      voxelsniper.brush.ellipse
      voxelsniper.brush.ellipsoid
      voxelsniper.brush.entity
      voxelsniper.brush.entityremoval
      voxelsniper.brush.eraser
      voxelsniper.brush.erode
      voxelsniper.brush.extrude
      voxelsniper.brush.filldown
      voxelsniper.brush.flatocean
      voxelsniper.brush.generatetree
      voxelsniper.brush.heatray
      voxelsniper.brush.jaggedline
      voxelsniper.brush.jockey
      voxelsniper.brush.lightning
      voxelsniper.brush.line
      voxelsniper.brush.move
      voxelsniper.brush.ocean
      voxelsniper.brush.overlay
      voxelsniper.brush.painting
      voxelsniper.brush.pull
      voxelsniper.brush.punish
      voxelsniper.brush.randomerode
      voxelsniper.brush.regeneratechunk
      voxelsniper.brush.ring
      voxelsniper.brush.rot2d
      voxelsniper.brush.rot2dvert
      voxelsniper.brush.rot3d
      voxelsniper.brush.ruler
      voxelsniper.brush.scanner
      voxelsniper.brush.set
      voxelsniper.brush.setredstoneflip
      voxelsniper.brush.setredstonerotate
      voxelsniper.brush.shellball
      voxelsniper.brush.shellset
      voxelsniper.brush.shellvoxel
      voxelsniper.brush.signoverwrite
      voxelsniper.brush.snipe
      voxelsniper.brush.snowcone
      voxelsniper.brush.spiralstaircase
      voxelsniper.brush.splatterball
      voxelsniper.brush.splatterdisc
      voxelsniper.brush.splatteroverlay
      voxelsniper.brush.splattervoxel
      voxelsniper.brush.splattervoxeldisc
      voxelsniper.brush.spline
      voxelsniper.brush.stamp
      voxelsniper.brush.stencil
      voxelsniper.brush.stencillist
      voxelsniper.brush.threepointcircle
      voxelsniper.brush.treesnipe
      voxelsniper.brush.triangle
      voxelsniper.brush.underlay
      voxelsniper.brush.voltmeter
      voxelsniper.brush.voxel
      voxelsniper.brush.voxeldisc
      voxelsniper.brush.voxeldiscface
      voxelsniper.brush.warp
  voxelsniper.brush.ball:
    default: op
  voxelsniper.brush.biome:
    default: op
  voxelsniper.brush.blendball:
    default: op
  voxelsniper.brush.blenddisc:
    default: op
  voxelsniper.brush.blendvoxel:
    default: op
  voxelsniper.brush.blendvoxeldisc:
    default: op
  voxelsniper.brush.blob:
    default: op
  voxelsniper.brush.blockreset:
    default: op
  voxelsniper.brush.blockresetsurface:
    default: op
  voxelsniper.brush.canyon:
    default: op
  voxelsniper.brush.canyonselection:
    default: op
  voxelsniper.brush.checkervoxeldisc:
    default: op
  voxelsniper.brush.cleansnow:
    default: op
  voxelsniper.brush.clonestamp:
    default: op
  voxelsniper.brush.comet:
    default: op
  voxelsniper.brush.copypasta:
    default: op
  voxelsniper.brush.cylinder:
    default: op
  voxelsniper.brush.disc:
    default: op
  voxelsniper.brush.discface:
    default: op
  voxelsniper.brush.dome:
    default: op
  voxelsniper.brush.drain:
    default: op
  voxelsniper.brush.ellipse:
    default: op
  voxelsniper.brush.ellipsoid:
    default: op
  voxelsniper.brush.entity:
    default: op
  voxelsniper.brush.entityremoval:
    default: op
  voxelsniper.brush.eraser:
    default: op
  voxelsniper.brush.erode:
    default: op
  voxelsniper.brush.extrude:
    default: op
  voxelsniper.brush.filldown:
    default: op
  voxelsniper.brush.flatocean:
    default: op
  voxelsniper.brush.generatetree:
    default: op
  voxelsniper.brush.heatray:
    default: op
  voxelsniper.brush.jaggedline:
    default: op
  voxelsniper.brush.jockey:
    default: op
  voxelsniper.brush.lightning:
    default: op
  voxelsniper.brush.line:
    default: op
  voxelsniper.brush.move:
    default: op
  voxelsniper.brush.ocean:
    default: op
  voxelsniper.brush.overlay:
    default: op
  voxelsniper.brush.painting:
    default: op
  voxelsniper.brush.pull:
    default: op
  voxelsniper.brush.punish:
    default: op
  voxelsniper.brush.randomerode:
    default: op
  voxelsniper.brush.regeneratechunk:
    default: op
  voxelsniper.brush.ring:
    default: op
  voxelsniper.brush.rot2d:
    default: op
  voxelsniper.brush.rot2dvert:
    default: op
  voxelsniper.brush.rot3d:
    default: op
  voxelsniper.brush.ruler:
    default: op
  voxelsniper.brush.scanner:
    default: op
  voxelsniper.brush.set:
    default: op
  voxelsniper.brush.setredstoneflip:
    default: op
  voxelsniper.brush.setredstonerotate:
    default: op
  voxelsniper.brush.shellball:
    default: op
  voxelsniper.brush.shellset:
    default: op
  voxelsniper.brush.shellvoxel:
    default: op
  voxelsniper.brush.signoverwrite:
    default: op
  voxelsniper.brush.snipe:
    default: op
  voxelsniper.brush.snowcone:
    default: op
  voxelsniper.brush.spiralstaircase:
    default: op
  voxelsniper.brush.splatterball:
    default: op
  voxelsniper.brush.splatterdisc:
    default: op
  voxelsniper.brush.splatteroverlay:
    default: op
  voxelsniper.brush.splattervoxel:
    default: op
  voxelsniper.brush.splattervoxeldisc:
    default: op
  voxelsniper.brush.spline:
    default: op
  voxelsniper.brush.stamp:
    default: op
  voxelsniper.brush.stencil:
    default: op
  voxelsniper.brush.stencillist:
    default: op
  voxelsniper.brush.threepointcircle:
    default: op
  voxelsniper.brush.treesnipe:
    default: op
  voxelsniper.brush.triangle:
    default: op
  voxelsniper.brush.underlay:
    default: op
  voxelsniper.brush.voltmeter:
    default: op
  voxelsniper.brush.voxel:
    default: op
  voxelsniper.brush.voxeldisc:
    default: op
  voxelsniper.brush.voxeldiscface:
    default: op
  voxelsniper.brush.warp:
    default: op
