blank_issues_enabled: false
contact_links:
  - name: IntellectualSites Discord
    url: https://discord.gg/intellectualsites
    about: Our support Discord, please ask questions and seek support here.
  - name: VoxelSniper Wiki
    url: https://voxelsniper.fandom.com/wiki/VoxelSniper_Wiki
    about: Look at the wiki page for answers for setup instructions command syntax and more.
